### ISSUE TITLE
Migrate to Kotlin

### ISSUE THREAD

**Issue by raghavtilak** [raghavtilak/SimpleDragSwipeRV#1]

**Comment by pawanchauhan043** [comment]
Hey, I can migrate this to kotlin. Could you please assign this to me?

**Comment by raghavtilak** [comment]
Hey @pawanchauhan043 yeah sure 
Go for it 👍

**Comment by pawanchauhan043** [comment]
Hey @raghavtilak , I have created a PR against master with the migrated code in kotlin.

**Comment by raghavtilak** [comment]
Great work @pawanchauhan043 😄 
Thanks for your contribution #4  ✌🏻
